services:
  many-form:
    image: many-form
    ports:
      - 3000:3000
    environment:
      - TZ=${TIMEZONE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - N8N_CHAT_URL=${N8N_CHAT_URL}
      - N8N_CHAT_FORM_URL=${N8N_CHAT_FORM_URL}

  n8n:
    image: n8nio/n8n:1.101.0
    container_name: n8n
    restart: always
    ports:
      - '5678:5678'
    environment:
      - GENERIC_TIMEZONE=${TIMEZONE}
      # - N8N_HOST=0.0.0.0
      # - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ./data_n8n:/home/node/.n8n
